### ISSUE TITLE
Type error because memberContext ist undefined

### ISSUE THREAD

**Issue by benthillerkus** [LBBO/netflix-migrate#37] opened 2019-08-19 12:20 UTC
No matter what I do, I get the error message:
![image](https://user-images.githubusercontent.com/29630575/63264909-88edb300-c28c-11e9-8db1-e0e3110c76d2.png)

**Comment by argoolsbee** [comment] 2019-09-02 22:03
I got this same error, and found it was because I was putting the wrong Netflix password for the account at the prompt.

**Comment by LBBO** [comment] 2019-09-04 06:04
Precicely what @argoolsbee said. I can reproduce this error by entering incorrect login information but with the correct information, everything works just fine. If you'd like, you can open an issue in LBBO/node-netflix2 so that wrong login data throws its own error.

Please check your login data and close this issue if that fixed it.

**Comment by ogierm** [comment] 2019-09-04 14:17
Well my Login data was definitely correct, because I tried it multiple times either by handtyping or copy pasting the password.
Maybe the issue is that the profile I tried to access has has space characters?

**Comment by argoolsbee** [comment] 2019-09-04 14:36
I can't find it now, but I remember seeing the same error could occur if the netflix subscription was inactive.

**Comment by LBBO** [comment] 2019-09-09 09:16
@argoolsbee you are probably referring to #24 and yes, an inactive account would probably cause this exact or a very similar error message. As I don't have an inactive account, I can't check that.

@ogierm If your profile name includes a space, you can just surround it with quote marks like so:

```bash
netflix-migrate --email your@email.com --profile "Your profile name" --export netflixData.json
```

However, the problem is your actual login (with email and password). If the login had completed, the script would have logged `Switching to profile Thorsten`. Since it didn't the crash happened during login. Does your password contain any characters that might confuse the power shell? I'm especially thinking of quotation marks or backslashes. If it does, could you try escaping them?

Also, could you try logging in to your account with your browser using the exact same data? If that doesn't work, netflix-migrate won't be able to login either.

**Comment by ogierm** [comment] 2019-09-09 21:49
I can login with the data it is definitely correct (I have to login per hand each time I open Netflix on my TV, because it constantly "forgets" the session)

Since I already deleted the account data I wanted to have I haven't touched it after writing the issue.


I guess I'll expand a bit on the situation I had. Basically my profile was the first profile on the account. We wanted to use Netflix on the TV, but the Netflix App on the TV doesn't support profiled (the TV is from 2012) so I had to basically give up my profile and start a new one. I wanted to use the tool to move over some data to my new profile.
I renamed my old profile to "Thorsten der TV" and added a new profile which had the name of my old profile. Besides the spaces the names didn't use any crazy characters.
I assumed the spaces were a problem so I tried wrapping it with quotation marks, only using the first word before the space etc. Basically everything you do when troubleshooting.

To be honest I don't really have a use case for this anymore so yeah. If you want me to test something specific I can do that, but beyond that I don't need it to work anymore.

**Comment by ishefi** [comment] 2020-03-31 07:40
I get this error as well. I'm sure credentials are correct. My account is deactivated though (doesn't happen for an activated account)

**Comment by KevinAlexandro** [comment] 2020-08-30 04:41
Has the issue been fixed? Let me know if I can help.

**Comment by LBBO** [comment] 2020-08-30 10:11
@KevinAlexandro I don't think so, as I haven't been able to reproduce the issue. Is there anything special about your account (such as unusual characters or the account being deactivated) and have you double-checked for correct spelling? I guess, any additional information that could help me reproduce this issue would help!

**Comment by KevinAlexandro** [comment] 2020-08-30 17:05
I am trying to migrate between an account that will be inactive on Monday and another one which is active. Also, I tried to migrate the other way around but I got the same error when the login takes place. I get the following error:

![netflixMigrateError](https://user-images.githubusercontent.com/32605942/91664983-3a3a4200-eab8-11ea-8598-ff596564d9b1.PNG)

I thought that the issue was related with the netflix2 version so I tried updating with the latest available version I found, but the issue persisted. Then I tried with another OS (Ubuntu 20LTS and Windows 10), but the issue persisted.

Is there any chance I need an old version of netflix2, the one used when migrate Netflix was released?

**Comment by KevinAlexandro** [comment] 2020-08-30 17:06
I am trying to migrate between an account that will be inactive on Monday and another one which is active. Also, I tried to migrate the other way around but I got the same error when the login takes place. I get the following error:

![netflixMigrateError](https://user-images.githubusercontent.com/32605942/91665154-3529c280-eab9-11ea-90f6-5cb7f384ce3c.PNG)

I thought that the issue was related with the netflix2 version so I tried updating with the latest available version I found, but the issue persisted. Then I tried with another OS (Ubuntu 20LTS and Windows 10), but the issue persisted.

Is there any chance I need an old version of netflix2, the one used when migrate Netflix was released?

**Comment by KevinAlexandro** [comment] 2020-08-30 17:07
I am trying to migrate between an account that will be inactive on Monday and another one which is active. Also, I tried to migrate the other way around but I got the same error when the login takes place. I get the following error:

![netflixMigrateError](https://user-images.githubusercontent.com/32605942/91665184-699d7e80-eab9-11ea-9b40-ad88ed9e34c7.PNG)

I thought that the issue was related with the netflix2 version so I tried updating with the latest available version I found, but the issue persisted. Then I tried with another OS (Ubuntu 20LTS and Windows 10), but the issue persisted.

Is there any chance I need an old version of netflix2, the one used when migrate Netflix was released?

**Comment by LBBO** [comment] 2020-09-12 10:35
First of all, sorry for taking so long to get back to you. I really hope you didn't loose your account's data because of this!

After doing some research, I was able to consistently reproduce the following behavior:

1. Use netflix-migrate in some way with correct login data. This command will succeed
2. Execute any other netflix-migrate command (even the exact same command as in 1) and it will fail.

The problem might be that Netflix doesn't allow two sessions from the same network. If I wait a few minutes after the successful command, I can execute another command successfully and the command after that will fail again (if I don't wait long enough). This might be fixable by logging off after every command, but I haven't gotten to that yet.

@KevinAlexandro and @jn-harvey (from #46): did your errors occur after running netflix-migrate once successfully? Perhaps the export worked, but then the import didn't work. And if so, could you try the import again and see if it works?

**Comment by LBBO** [comment] 2020-09-12 11:17
It's also worth noting that you can't have an open tab with Netflix while using netflix-migrate. That's definitely something I will add to the README

**Comment by pinkbunny1** [comment] 2020-09-14 15:56
I could log in to the Netflix account successfully and had everything closed and executed the command but I have the same error message.

**Comment by LBBO** [comment] 2020-09-15 11:17
Ok, after doing some more experimentation, my current guess is that Google reCAPTCHA is stopping most (but not all) login attempts. Here's why I think that:

1. I just cannot for the life of me reproduce this issue consistently. Without changing any code at all (or anything else, for that matter - I just leave my computer for a few minutes), some requests go through and some fail.
2. After checking archive.org, it looks like Netflix added Google reCAPTCHA around [Feb 27 2020](https://web.archive.org/web/20200227165819/https://www.netflix.com/login), which roughly coincides with this issue gaining traction. It was opened in 2019, but it seems to have gotten way more common now and I also wasn't able to reproduce it back then.

I'm not really sure how to confirm this theory (please feel free to share any ideas you might have on that!). And even if I was able to confirm it, I have no idea how to get around Google's reCAPTCHA. One option might be to have the user enter their authUrl from an active browser session, but that would be a pretty terrible UX.

For now, all I can suggest is trying it again. Perhaps wait a few minutes in between requests, maybe even a day, I just don't know.  Please let me know how things go, though!

**Comment by pieter-mastenbroek** [comment] 2020-10-22 19:03
I have the same issue running Ubuntu in WSL2. 
ill try to check after some time, maybe in an hour or in a day.

**Comment by shivaramg** [comment] 2020-12-20 17:16
I was able to export the data fine but I get the error when I import. 
I made sure that the password is correct.
May be I will wait for a day or two and try since I just created my netflix account

**Comment by dstronczak** [comment] 2020-12-23 08:43
Got the very same issue. Export works fine, but I get the very same error every time I import. So far I tried:
- waiting a day
- using both the existing profile name and a nonexisting profile name as an import target

**Comment by dstronczak** [comment] 2020-12-23 12:58
@LBBO 
I really care about solving this issue, if you suggest some ways of debugging the problem (like getting more descriptive error) I could try to do some investigation myself. I'd really appreciate that :)

**Comment by LBBO** [comment] 2020-12-23 21:02
Hey @dstronczak!

Sorry for not getting back to you for a while. To be honest, I haven't looked into this issue for a while, so I might be forgetting details or my information might be outdated.

One thing you could do is to compare the Netflix response to responses from other sites that use reCAPTCHA. This way, we might be able to confirm that reCAPTCHA is actually the source of this issue.

As for other ideas: it might be possible to create a browser plugin (or even a bookmarklet?) that either brings this plugin's functionality to the browser or transmits any necessary data to the command line tool. Turning this project into a plugin actually makes a lot of sense, especially in terms of the UI. The user could then just log in on their own and the plugin would then execute pretty much the same scripts, I think. There might be issues with limitations for plugin's network traffic, though.

There are more important things for me to take care of in the next weeks and months, so it might take a while before I get around to looking into this change, though. I wouldn't expect it to happen before March.

**Comment by laithsaid** [comment] 2020-12-31 11:36
Is it possible to access the API by other means and give the correct reCAPTCHA?

**Comment by ncesar** [comment] 2021-01-06 00:38
same problem here, I was able to export but when I tried to import i got undefined :( going to wait a few hours to try again

**Comment by pedroluisneves** [comment] 2021-01-09 23:44
I´m facing the same issue.
Some how I was able to export, however after many tries, but import seams to be impossible.
Is there any way to edit netflix2.js to manually add a valid token after the browser login?

**Comment by LBBO** [comment] 2021-01-23 18:31
Hey everyone!

I really like the idea of manually logging in and then just adding some token as a parameter. I will look into it these next days and will get back to you once I have an update.

**Comment by LBBO** [comment] 2021-01-24 17:41
Alright, I have a working prototype!

Netflix-migrate will no longer email address and username. Instead, users must manually log in to Netflix, open the console, and copy the cookie by running `document.cookie`. That value will then have to be provided to netflix-migrate and everything should work (at least, it does for me).

Let me turn this into something actually usable (instead of hard-coding the cookie 😅 etc.) and then a beta version will be on its way.

**Comment by LBBO** [comment] 2021-01-25 13:57
Hey everyone,

I just published a beta version that should fix this issue! You can install it with `npm i netflix-migrate@beta` or run it directly with `npx netflix-migrate@beta ...`. However, please be aware that the rest of the commands have changed. For more information on that, please refer to the README I linked below.

Sadly, I was wrong about how the cookie could be extracted. Apparently, a part of the cookie is needed that cannot be extracted via JS, which I accidentally missed last evening. The cookie must, instead, be extracted from the network tab, which is a bit more complicated. I wrote some instructions on how to do this, though. You can find them in [the README of the branch I'm currently working on](https://github.com/LBBO/netflix-migrate/blob/cookie-login/README.md).

If you'd like to, please feel free to give this a try and leave some feedback in #54 if you run into any trouble or if you find the instructions to be unclear in any way.

**Comment by weq** [comment] 2021-02-07 14:50
Hi, I tried out the beta and it is bugging over import due to several reasons it seems. At first it bugs out because of the version number in the JSON. Tried to edit that to 0.3.6 and it moves a bit forward but it halts here:
```
npx: installed 146 in 8.822s
Using new Netflix2 class!
Logging into Netflix using Cookies
Login successful!
Switching to profile Hilde
Successfully switched profile!
Reading data from hilde3_netflix.json
Found rating history and viewing history
Setting rating for The White Tiger: thumbs up
TypeError: Request with GET/HEAD method cannot have body
    at new Request (C:\Users\micro\AppData\Roaming\npm-cache\_npx\21008\node_modules\netflix-migrate\node_modules\node-fetch\lib\index.js:1199:10)
    at C:\Users\micro\AppData\Roaming\npm-cache\_npx\21008\node_modules\netflix-migrate\node_modules\node-fetch\lib\index.js:1409:19
    at new Promise (<anonymous>)
    at fetch (C:\Users\micro\AppData\Roaming\npm-cache\_npx\21008\node_modules\netflix-migrate\node_modules\node-fetch\lib\index.js:1407:9)
    at Netflix.__request (C:\Users\micro\AppData\Roaming\npm-cache\_npx\21008\node_modules\netflix-migrate\node_modules\netflix2\lib\netflix2.js:58:18)
    at Netflix.__apiRequest (C:\Users\micro\AppData\Roaming\npm-cache\_npx\21008\node_modules\netflix-migrate\node_modules\netflix2\lib\netflix2.js:501:35)
    at Netflix.__setRating (C:\Users\micro\AppData\Roaming\npm-cache\_npx\21008\node_modules\netflix-migrate\node_modules\netflix2\lib\netflix2.js:355:35)
    at Netflix.setThumbRating (C:\Users\micro\AppData\Roaming\npm-cache\_npx\21008\node_modules\netflix-migrate\node_modules\netflix2\lib\netflix2.js:381:16)
    at C:\Users\micro\AppData\Roaming\npm-cache\_npx\21008\node_modules\netflix-migrate\main.js:255:19
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
Error: There was something wrong with your request. For more information, see previous log statements.
    at Netflix.__apiRequest (C:\Users\micro\AppData\Roaming\npm-cache\_npx\21008\node_modules\netflix-migrate\node_modules\netflix2\lib\netflix2.js:509:13)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async Netflix.__setRating (C:\Users\micro\AppData\Roaming\npm-cache\_npx\21008\node_modules\netflix-migrate\node_modules\netflix2\lib\netflix2.js:355:24)
    at async Netflix.setThumbRating (C:\Users\micro\AppData\Roaming\npm-cache\_npx\21008\node_modules\netflix-migrate\node_modules\netflix2\lib\netflix2.js:381:5)
    at async C:\Users\micro\AppData\Roaming\npm-cache\_npx\21008\node_modules\netflix-migrate\main.js:255:5
    at async main (C:\Users\micro\AppData\Roaming\npm-cache\_npx\21008\node_modules\netflix-migrate\main.js:51:4)
Error: Couldn't set thumb rating. For more information, see previous log statements.
    at Netflix.__setRating (C:\Users\micro\AppData\Roaming\npm-cache\_npx\21008\node_modules\netflix-migrate\node_modules\netflix2\lib\netflix2.js:362:13)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async Netflix.setThumbRating (C:\Users\micro\AppData\Roaming\npm-cache\_npx\21008\node_modules\netflix-migrate\node_modules\netflix2\lib\netflix2.js:381:5)
    at async C:\Users\micro\AppData\Roaming\npm-cache\_npx\21008\node_modules\netflix-migrate\main.js:255:5
    at async main (C:\Users\micro\AppData\Roaming\npm-cache\_npx\21008\node_modules\netflix-migrate\main.js:51:4)
Error: Could not set thumb rating for The White Tiger. For more information, please see previous log statements.
    at C:\Users\micro\AppData\Roaming\npm-cache\_npx\21008\node_modules\netflix-migrate\main.js:263:10
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async main (C:\Users\micro\AppData\Roaming\npm-cache\_npx\21008\node_modules\netflix-migrate\main.js:51:4)
```

**Comment by loiu92** [comment] 2021-08-21 09:29
memberContext seems to be renamed to loginContext. I can make the login working by changing memberContent to loginContext but then i have an issue about profile guid

**Comment by StevieApp** [comment] 2021-09-17 15:58
I'm trying to use the cookie from my account on netflix2 and email and password  on netflix-migrate and  I'm receiving the same issue  [Cannot read property 'data' of undefined](https://github.com/LBBO/netflix-migrate/issues/37)

**Comment by StevieApp** [comment] 2021-09-17 16:00
> memberContext seems to be renamed to loginContext. I can make the login working by changing memberContent to loginContext but then i have an issue about profile guid

If this is the issue then the netflix2 part is the issue

**Comment by card13** [comment] 2021-11-08 00:32
Getting same error with master branch. Did lots of reading, about to download and try https://github.com/LBBO/netflix-migrate/tree/cookie-login.

**Comment by seabird** [comment] 2022-09-20 12:50
OK, so is the solution for the import: use another computer? Don't have a 4K account? Have a simple profile name?

Or is it just open and not solved yet?

I would love to transfer my old profile to my new account

**Comment by seabird** [comment] 2022-09-20 18:24
> OK, so is the solution for the import: use another computer? Don't have a 4K account? Have a simple profile name?
> 
> Or is it just open and not solved yet?
> 
> I would love to transfer my old profile to my new account

OK, so I tried again, but this time a clean install from my debian server. Same result. So I shortened the command and simplified my password. To my surprise: import worked.

Unfortunately as indicated in the read me: only ratings were imported (as far as I can tell). Viewed or lists remain pending.

Hoping there is a update for this in the near future.

For.information: profile name was the same and new profile is a 4K account.

**Comment by LBBO** [comment] 2022-10-23 11:16
Since Netflix added native support for account transfer (including viewing history and My List 🎉), I'm archiving this project (see #73). Please refer to [their official documentation](https://help.netflix.com/en/node/124844) if you still need to transfer you account data.

**Closed by LBBO** 2022-10-23 11:16 UTC
