### ISSUE TITLE
import not working

### ISSUE THREAD

**Issue by jn-harvey** [LBBO/netflix-migrate#46] opened 2020-09-10 12:58 UTC
Every time I'm triying to import, I receive this error message (my password is ok) :
Logging into Netflix as hello.dear@cool.com
/usr/local/lib/node_modules/netflix-migrate/node_modules/netflix2/lib/netflix2.js:465
      self.authUrls[url] = context.netflix.reactContext.models.memberContext.data.userInfo.authURL
                                                                             ^

TypeError: Cannot read property 'data' of undefined
    at Request._callback (/usr/local/lib/node_modules/netflix-migrate/node_modules/netflix2/lib/netflix2.js:465:78)
    at Request.self.callback (/usr/local/lib/node_modules/netflix-migrate/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/netflix-migrate/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at Gunzip.<anonymous> (/usr/local/lib/node_modules/netflix-migrate/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at Gunzip.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

Thank you.

**Comment by LBBO** [comment] 2020-09-12 10:28
Closing this as a duplicate of #37

**Closed by LBBO** 2020-09-12 10:28 UTC
