### ISSUE TITLE
TypeError: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by k0pernikus** [LBBO/netflix-migrate#47] opened 2020-09-30 19:36 UTC
There's an error when tyring to export data:

```
/home/philipp/.nvm/versions/node/v10.21.0/lib/node_modules/netflix-migrate/node_modules/netflix2/lib/netflix2.js:465
      self.authUrls[url] = context.netflix.reactContext.models.memberContext.data.userInfo.authURL
                                                                             ^

TypeError: Cannot read property 'data' of undefined
    at Request._callback (/home/philipp/.nvm/versions/node/v10.21.0/lib/node_modules/netflix-migrate/node_modules/netflix2/lib/netflix2.js:465:78)
    at Request.self.callback (/home/philipp/.nvm/versions/node/v10.21.0/lib/node_modules/netflix-migrate/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/home/philipp/.nvm/versions/node/v10.21.0/lib/node_modules/netflix-migrate/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:198:13)
    at Gunzip.<anonymous> (/home/philipp/.nvm/versions/node/v10.21.0/lib/node_modules/netflix-migrate/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:286:20)
    at Gunzip.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by LBBO** [comment] 2020-09-30 19:55
Duplicate of #37

**Closed** 2020-09-30 19:55 UTC
