### ISSUE TITLE
TypeError: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by shayenek** [LBBO/netflix-migrate#48] opened 2020-10-16 09:33 UTC
Hello!

I have used export in the past and it worked a couple of times but very often it would give me the error from the title. For a few days i've been trying to get it to work again with no success. I get that error every single time I try to export a profile.

TypeError: Cannot read property 'data' of undefined
    at Request._callback (C:\Users\Shayenek\AppData\Roaming\npm\node_modules\netflix-migrate\node_modules\netflix2\lib\netflix2.js:465:78)
    at Request.self.callback (C:\Users\Shayenek\AppData\Roaming\npm\node_modules\netflix-migrate\node_modules\request\request.js:185:22)
    at Request.emit (events.js:311:20)
    at Request.<anonymous> (C:\Users\Shayenek\AppData\Roaming\npm\node_modules\netflix-migrate\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:311:20)
    at Gunzip.<anonymous> (C:\Users\Shayenek\AppData\Roaming\npm\node_modules\netflix-migrate\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:417:28)
    at Gunzip.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

Is there a possible solution to that problem?

**Comment by LBBO** [comment] 2020-10-21 07:58
Ultimately, the problem is that Netflix started using Google's reCAPTCHA. For more details, please refer to #37.

I'm closing this issue as it's a duplicate of said issue.

**Closed by LBBO** 2020-10-21 07:58 UTC
